version: 2.1

orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build-and-deploy-frontend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: 14.17.1
      - aws-cli/setup
      - run:
          name: FrontEnd Install
          command: |
            npm run frontend:install
      - run:
          name: FrontEnd Build
          command: |
            npm run frontend:build
      - run:
          name: FrontEnd Deploy
          command: |
            npm run frontend:deploy
  build-and-deploy-backend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: 14.17.1
      - aws-cli/setup
      - eb/setup
      - run:
          name: BackEnd Install
          command: |
            npm run backend:install
      - run:
          name: BackEnd Build
          command: |
            npm run backend:build
      - run:
          name: BackEnd Deploy
          command: |
            npm run backend:deploy

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy-frontend:
          filters:
            branches:
              only: main
      - build-and-deploy-backend:
          filters:
            branches:
              only: main
