version: 2.1

orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build-and-deploy-front-end:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # Installing the frontend dependencies
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install

      # Building the frontend
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
build-and-deploy-back-end:
  docker:
    - image: "cimg/base:stable"
  steps:
    - node/install
    - checkout
    # Installing the backend dependencies
    - run:
        name: Back-End Install
        command: |
          npm run backend:install
    - run:
        name: Back-End Build
        command: |
          npm run backend:build

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy-front-end:
          filters:
            branches:
              only: main
      - build-and-deploy-back-end:
          filters:
            branches:
              only: main
